### ISSUE TITLE
Request to Become a Contributor

### ISSUE THREAD

**Issue by HardMax71** [kamal0803/flask-cafe-application#1]
Hi,

  I hope you are doing well. I'm Max, and I am very interested in contributing to your project (to train all this contributing stuff, play with Flask and so on). I couldn't find `CONTRIBUTING.md` file in the repository. Could you please provide some guidelines on how I can start contributing? Or will it be enough to fork your repo and then ask for merging my PR (Pull request) with explicit list of things added/changed?

Thank you!

Best regards,
Max

**Comment by kamal0803** [comment]
Hi Max,

Thanks for reaching out. Great to hear that you would like to contribute. Pleease feel free to fork the repo and you can send me list of amendments, and I would be happy to merge them.

Please feel free to reach out in case of further queries.

Have a good day.

Thanks,
Kamal
